# Generated by Django 2.2.5 on 2023-12-04 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
    ]
