# Generated by Django 2.1.5 on 2019-03-31 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_post_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='ComplexityPost',
        ),
    ]
