# Generated by Django 2.1.5 on 2019-03-31 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20190331_2055'),
    ]

    operations = [
        migrations.CreateModel(
            name='MastersPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_a', models.CharField(max_length=5)),
                ('post_b', models.CharField(max_length=5)),
                ('post_k', models.CharField(max_length=5)),
                ('post_i', models.CharField(default=0, max_length=5)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
