# Generated by Django 2.2 on 2019-04-15 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_masterspost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterspost',
            name='post_a',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='masterspost',
            name='post_b',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='masterspost',
            name='post_i',
            field=models.CharField(default=0, max_length=2),
        ),
        migrations.AlterField(
            model_name='masterspost',
            name='post_k',
            field=models.CharField(default=0, max_length=2),
        ),
    ]
