# Generated by Django 2.2 on 2019-04-15 12:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_auto_20190415_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterspost',
            name='post_a',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxLengthValidator(3)]),
        ),
        migrations.AlterField(
            model_name='masterspost',
            name='post_b',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxLengthValidator(3)]),
        ),
        migrations.AlterField(
            model_name='masterspost',
            name='post_i',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxLengthValidator(3)]),
        ),
        migrations.AlterField(
            model_name='masterspost',
            name='post_k',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxLengthValidator(3)]),
        ),
    ]
