# Generated by Django 2.2 on 2019-04-20 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_auto_20190415_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='complexitypost',
            name='guess',
            field=models.CharField(default='None', max_length=25),
        ),
        migrations.AlterField(
            model_name='complexitypost',
            name='post',
            field=models.CharField(max_length=25),
        ),
    ]
