# Generated by Django 2.2 on 2019-04-20 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_auto_20190420_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complexitypost',
            name='guess',
            field=models.CharField(max_length=25),
        ),
    ]
